{"uid":"80eb41b547494032","name":"test_get_route_by_id_not_found","fullName":"tests.integration.route_serv.test_get_by_id_non_existen_route_it#test_get_route_by_id_not_found","historyId":"c41acb797d98599f64138aec77c8ad87","time":{"start":1759303646229,"stop":1759303646229,"duration":0},"status":"broken","statusMessage":"socket.gaierror: [Errno -3] Temporary failure in name resolution","statusTrace":"request = <SubRequest 'db_session' for <Coroutine test_get_route_by_id_not_found>>\nkwargs = {}, func = <function db_session at 0x7f7ff5698b80>\nevent_loop_fixture_id = 'event_loop'\nsetup = <function _wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.setup at 0x7f7ff38da660>\nsetup_task = <Task finished name='Task-48' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.setup() done, d.../python3.13/site-packages/pytest_asyncio/plugin.py:339> exception=gaierror(-3, 'Temporary failure in name resolution')>\n\n    @functools.wraps(fixture)\n    def _asyncgen_fixture_wrapper(request: FixtureRequest, **kwargs: Any):\n        func = _perhaps_rebind_fixture_func(fixture, request.instance)\n        event_loop_fixture_id = _get_event_loop_fixture_id_for_async_fixture(\n            request, func\n        )\n        event_loop = request.getfixturevalue(event_loop_fixture_id)\n        kwargs.pop(event_loop_fixture_id, None)\n        gen_obj = func(**_add_kwargs(func, kwargs, event_loop, request))\n    \n        async def setup():\n            res = await gen_obj.__anext__()  # type: ignore[union-attr]\n            return res\n    \n        context = contextvars.copy_context()\n        setup_task = _create_task_in_context(event_loop, setup(), context)\n>       result = event_loop.run_until_complete(setup_task)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py:345: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py:725: in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py:340: in setup\n    res = await gen_obj.__anext__()  # type: ignore[union-attr]\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\ntests/conftest.py:101: in db_session\n    async with engine.begin() as conn:\n               ^^^^^^^^^^^^^^\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py:214: in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py:1066: in begin\n    async with conn:\n               ^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/base.py:121: in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py:274: in start\n    await greenlet_spawn(self.sync_engine.connect)\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py:201: in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py:3277: in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py:143: in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py:3301: in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:447: in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:1264: in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:711: in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/impl.py:177: in _do_get\n    with util.safe_reraise():\n         ^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:224: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/impl.py:175: in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:388: in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:673: in __init__\n    self.__connect()\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:899: in __connect\n    with util.safe_reraise():\n         ^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py:224: in __exit__\n    raise exc_value.with_traceback(exc_tb)\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py:895: in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/create.py:661: in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/default.py:629: in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py:964: in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py:132: in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py:196: in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connection.py:2421: in connect\n    return await connect_utils._connect(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py:1075: in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py:1049: in _connect\n    conn = await _connect_addr(\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py:886: in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py:931: in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n../../../.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py:802: in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py:1122: in create_connection\n    infos = await self._ensure_resolved(\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py:1508: in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py:939: in getaddrinfo\n    return await self.run_in_executor(\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/concurrent/futures/thread.py:59: in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nhost = 'test-db', port = 5432, family = 0, type = <SocketKind.SOCK_STREAM: 1>\nproto = 0, flags = 0\n\n    def getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):\n        \"\"\"Resolve host and port into list of address info entries.\n    \n        Translate the host/port argument into a sequence of 5-tuples that contain\n        all the necessary arguments for creating a socket connected to that service.\n        host is a domain name, a string representation of an IPv4/v6 address or\n        None. port is a string service name such as 'http', a numeric port number or\n        None. By passing None as the value of host and port, you can pass NULL to\n        the underlying C API.\n    \n        The family, type and proto arguments can be optionally specified in order to\n        narrow the list of addresses returned. Passing zero as a value for each of\n        these arguments selects the full range of results.\n        \"\"\"\n        # We override this function since we want to translate the numeric family\n        # and socket type values to enum constants.\n        addrlist = []\n>       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       socket.gaierror: [Errno -3] Temporary failure in name resolution\n\n/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/socket.py:977: gaierror","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1759303629149,"stop":1759303629218,"duration":69},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1759303629149,"stop":1759303629149,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1759303629149,"stop":1759303629149,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1759303629218,"stop":1759303629218,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"pytestconfig","time":{"start":1759303629218,"stop":1759303629218,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1759303629218,"stop":1759303629219,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop_policy","time":{"start":1759303629218,"stop":1759303629218,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"db_session","time":{"start":1759303646230,"stop":1759303646233,"duration":3},"status":"broken","statusMessage":"socket.gaierror: [Errno -3] Temporary failure in name resolution\n","statusTrace":"  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/_pytest/fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py\", line 345, in _asyncgen_fixture_wrapper\n    result = event_loop.run_until_complete(setup_task)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py\", line 725, in run_until_complete\n    return future.result()\n           ~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/pytest_asyncio/plugin.py\", line 340, in setup\n    res = await gen_obj.__anext__()  # type: ignore[union-attr]\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/Testing_and_debbug/Testing_and_debbug/tests/conftest.py\", line 101, in db_session\n    async with engine.begin() as conn:\n               ~~~~~~~~~~~~^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n               ^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py\", line 3277, in connect\n    return self._connection_cls(self)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py\", line 143, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/base.py\", line 3301, in raw_connection\n    return self.pool.connect()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 447, in connect\n    return _ConnectionFairy._checkout(self)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 711, in checkout\n    rec = pool._do_get()\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/impl.py\", line 175, in _do_get\n    return self._create_connection()\n           ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 388, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 673, in __init__\n    self.__connect()\n    ~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 899, in __connect\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/pool/base.py\", line 895, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/create.py\", line 661, in connect\n    return dialect.connect(*cargs, **cparams)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/engine/default.py\", line 629, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 964, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<20 lines>...\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n    ...<2 lines>...\n    )\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n    ...<6 lines>...\n    )\n    ^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/home/runner/.cache/pypoetry/virtualenvs/ppo-_4RQizgT-py3.13/lib/python3.13/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n        host, port)\n        ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py\", line 1122, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        (host, port), family=family,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        type=socket.SOCK_STREAM, proto=proto, flags=flags, loop=self)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py\", line 1508, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n                                  proto=proto, flags=flags)\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py\", line 939, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        None, getaddr_func, host, port, family, type, proto, flags)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/concurrent/futures/thread.py\", line 59, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/socket.py\", line 977, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[{"name":"event_loop::finalizer","time":{"start":1759303659684,"stop":1759303659684,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1759303659684,"stop":1759303659684,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_restore_policy","time":{"start":1759303659684,"stop":1759303659684,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1759303659684,"stop":1759303659684,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.route_serv"},{"name":"suite","value":"test_get_by_id_non_existen_route_it"},{"name":"host","value":"runnervm3ublj"},{"name":"thread","value":"2752-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.route_serv.test_get_by_id_non_existen_route_it"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":2,"unknown":0,"total":4},"items":[{"uid":"99460ee3a58f486e","status":"broken","statusDetails":"OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5434, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5434)","time":{"start":1759261828873,"stop":1759261828873,"duration":0}},{"uid":"26771ed59fa268b4","status":"passed","time":{"start":1758953677080,"stop":1758953677081,"duration":1}},{"uid":"4f57606ebb5b0dbd","status":"passed","time":{"start":1758951887190,"stop":1758951887191,"duration":1}}]},"tags":["asyncio"]},"source":"80eb41b547494032.json","parameterValues":[]}